### PR TITLE
add travisci validation

### PR DESCRIPTION
**Pull request by clamoriniere**

### CODE REVIEW

**Comment by dbenque-1a** [comment]
LGTM.

**Comment by dbenque-1a** [comment]
operator-sdk test local ./test/e2e --image kanary/operator:$TAG --kubeconfig $KUBECONFIG

I don't understand

**Comment by dbenque-1a** [comment]
operator-sdk test local ./test/e2e --image kanary/operator:$TAG --kubeconfig $KUBECONFIG

This is going to launch the e2e test. In the e2e test, we run a Kanary pod:
https://github.com/AmadeusITGroup/kanary/blob/master/test/e2e/kanary_test.go#L514

I don't understand how the version  of the Kanary pod that is used is the one that match the $TAG.

**Comment by clamoriniere** [comment]
@dbenque-1a the replacement is done inside the operator-sdk command: https://github.com/operator-framework/operator-sdk/blob/52ad33a4bda0f78bdc8acdc49586a670fc755de5/cmd/operator-sdk/test/local.go#L186
so before calling our code.

**Pull request merged**
