### PR TITLE
move to go 1.12 + migrate to go mod

### PR DESCRIPTION
**Pull request by Nexucis**

### CODE REVIEW

**Comment by clamoriniere** [comment]
Hi @Nexucis,
Thanks for opening this PR. 
It may be worth waiting that the "operator-fwk" used in this project migrates also to "go module" before doing it in this project.

PR go module support in "operator fwk": https://github.com/operator-framework/operator-sdk/pull/1001

**Comment by Nexucis** [comment]
For sure we can wait, but I don't think it'll will change anything. I think `go mod` can handle dep and since operator-fwk uses dep, it should be ok.

**Comment by Nexucis** [comment]
@clamoriniere the PR on operator fwk has been merged. I updated the PR accordingly, it should be safe to merge it now :)

**Review by clamoriniere — APPROVED** [review]
/lgtm

**Comment by Nexucis** [comment]
@clamoriniere I don't have the right to merge it by myself :)

**Comment by sdminonne** [comment]
Thanks for the contribution and thanks @clamoriniere  for the help

**Pull request merged**
